# Generated by Django 3.2.6 on 2021-09-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0005_auto_20210905_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerprofile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='developer/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='developer/project/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
