# Generated by Django 3.2.6 on 2021-09-05 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='otp',
            new_name='ot',
        ),
    ]
