# Generated by Django 3.2.6 on 2021-09-05 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_otp_customuser_ot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='ot',
            new_name='otp',
        ),
    ]
