# Generated by Django 3.2.6 on 2021-08-31 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='otp_code',
            new_name='token',
        ),
    ]
